[package]
name = "network-simple"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
simcore = "0.1"
dslab-network = { path = "../../crates/dslab-network" }
clap = { version = "4.1.9", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4"
sugars = "3.0.0"
