[package]
name = "dslab-models"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
dyn-clone = "1.0"
dslab-core = { path = "../dslab-core" }
rand = "0.8.4"
sugars = "3.0.0"
rustc-hash = "2.0"
